### ISSUE TITLE
Unable to install napari_nucleaizer plugin

### ISSUE THREAD

**Issue by ebouilhol** [etasnadi/napari_nucleaizer#4]
Hi, 

First of all, thank you very much for your work and bringing NucleAIzer to Napari !

I tried to install the plugin today, without success. I have an error stack from the plugin installation window but I was not able to find a solution, I hope you can help !

<details>

<summary> Complete output with Error stack</summary>
```Collecting napari-nucleaizer

Using cached napari_nucleaizer-0.2.4-py3-none-any.whl (24 kB)

Requirement already satisfied: napari in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari-nucleaizer) (0.4.18)

Requirement already satisfied: qtpy in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari-nucleaizer) (2.3.1)

Collecting jsonpickle (from napari-nucleaizer)

  Obtaining dependency information for jsonpickle from https://files.pythonhosted.org/packages/d3/25/6e0a450430b7aa194b0f515f64820fc619314faa289458b7dfca4a026114/jsonpickle-3.0.2-py3-none-any.whl.metadata

  Using cached jsonpickle-3.0.2-py3-none-any.whl.metadata (7.5 kB)

Requirement already satisfied: numpy in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari-nucleaizer) (1.25.2)

Requirement already satisfied: scikit-image in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari-nucleaizer) (0.21.0)
Requirement already satisfied: imageio in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari-nucleaizer) (2.31.2)

Collecting nucleaizer-backend (from napari-nucleaizer)

  Using cached nucleaizer_backend-0.2.1-py3-none-any.whl (98 kB)

Requirement already satisfied: pillow>=8.3.2 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from imageio->napari-nucleaizer) (10.0.0)

Requirement already satisfied: appdirs>=1.4.4 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (1.4.4)

Requirement already satisfied: app-model<0.3.0,>=0.1.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.2.0)

Requirement already satisfied: cachey>=0.2.1 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.2.1)

Requirement already satisfied: certifi>=2018.1.18 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (2023.7.22)

Requirement already satisfied: dask[array]!=2.28.0,>=2.15.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (2023.8.1)

Requirement already satisfied: jsonschema>=3.2.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (4.19.0)

Requirement already satisfied: lazy-loader>=0.2 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.3)

Requirement already satisfied: magicgui>=0.3.6 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.7.3)

Requirement already satisfied: napari-console>=0.0.6 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.0.8)

Requirement already satisfied: napari-plugin-engine>=0.1.9 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.2.0)

Requirement already satisfied: napari-svg>=0.1.7 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.1.10)

Requirement already satisfied: npe2>=0.5.2 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.7.2)

Requirement already satisfied: numpydoc>=0.9.2 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (1.5.0)

Requirement already satisfied: pint>=0.17 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.22)
Requirement already satisfied: psutil>=5.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (5.9.5)

Requirement already satisfied: psygnal>=0.3.4 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.9.3)

Requirement already satisfied: pydantic<2,>=1.9.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (1.10.12)

Requirement already satisfied: pygments>=2.6.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (2.16.1)

Requirement already satisfied: PyOpenGL>=3.1.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (3.1.7)

Requirement already satisfied: PyYAML>=5.1 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (6.0.1)

Requirement already satisfied: sphinx<5,>=4.3.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (4.5.0)

Requirement already satisfied: superqt>=0.4.1 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.5.3)

Requirement already satisfied: tifffile>=2020.2.16 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (2023.8.25)

Requirement already satisfied: toolz>=0.10.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.12.0)

Requirement already satisfied: tqdm>=4.56.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (4.66.1)

Requirement already satisfied: typing-extensions>=4.2.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (4.7.1)

Requirement already satisfied: vispy<0.13,>=0.12.1 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (0.12.2)

Requirement already satisfied: wrapt>=1.11.1 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (1.15.0)

Requirement already satisfied: pandas>=1.3.0 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (2.0.3)

Requirement already satisfied: scipy>=1.5.4 in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from napari->napari-nucleaizer) (1.11.2)

Requirement already satisfied: packaging in /home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages (from qtpy->napari-nucleaizer) (23.1)

Collecting Cython (from nucleaizer-backend->napari-nucleaizer)

  Obtaining dependency information for Cython from https://files.pythonhosted.org/packages/18/f1/c3918a7a367a17d5c07d8e576c51ba78fc807f214f748026876352f8b0c2/Cython-3.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata

  Using cached Cython-3.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)

Collecting albumentations (from nucleaizer-backend->napari-nucleaizer)

  Obtaining dependency information for albumentations from https://files.pythonhosted.org/packages/9b/f6/c486cedb4f75147232f32ec4c97026714cfef7c7e247a1f0427bc5489f66/albumentations-1.3.1-py3-none-any.whl.metadata

  Using cached albumentations-1.3.1-py3-none-any.whl.metadata (34 kB)

Collecting opencv-python>=4.5.1 (from nucleaizer-backend->napari-nucleaizer)

  Obtaining dependency information for opencv-python>=4.5.1 from https://files.pythonhosted.org/packages/f5/d0/2e455d894ec0d6527e662ad55e70c04f421ad83a6fd0a54c3dd73c411282/opencv_python-4.8.0.76-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata

  Using cached opencv_python-4.8.0.76-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)

Collecting tensorflow-gpu>=2.3 (from nucleaizer-backend->napari-nucleaizer)

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lbn52d0w/tensorflow-gpu_0b8834284e984ea99e98c9f1e5112e5a/setup.py", line 40, in <module>
          setuptools.setup()
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/__init__.py", line 77, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/dist.py", line 901, in parse_config_files
          self._finalize_requires()
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/dist.py", line 596, in _finalize_requires
          self._move_install_requirements_markers()
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/dist.py", line 636, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/home/ebouilhol/mambaforge/envs/napari-env/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. ```
</details>
I'm on Ubuntu 22.04.

I am running Napari on an conda environment with python==3.9.17 

I tried to make a 3.7 environment but it seems Napari does no longer support python 3.7, I had other issues launching napari with it. 

Please let me know if you need any kind of further informations.

Thanks for your help !

**Comment by etasnadi** [comment]
Hi,

I could reproduce the error with pip. I guess the install crashes because of the tensorflow-gpu requirement that is replaced by tensorflow in recent tf versions.

https://github.com/tensorflow/tensorflow/issues/60074

I will fix it soon and upload a new version to PyPI.

Thanks.

Best,
Ervin

**Comment by etasnadi** [comment]
I fixed the issue in https://github.com/etasnadi/nucleaizer_backend/commit/e726f93e3198668985a12ae47778483ec3cfb4ac.

The new versions (0.2.5) are uploaded to PyPI:
- https://pypi.org/project/napari-nucleaizer/0.2.5/
- https://pypi.org/project/nucleaizer-backend/0.2.5/

It is not visible yet in the plugin management GUI of Napari, but you can install the plugin manually by installing `napari-nucleaizer` into your environment manually (the previous version of `nucleaizer-backend` might be deleted first!).

I tested the manual install with pip and it seems to work.

**Comment by ebouilhol** [comment]
Thank you very much for your help, I tried and I can install it properly. 

I have an other issue, with the numpy version that no longer recognize np.bool (deprecated) somewhere in the code `AttributeError: module 'numpy' has no attribute 'bool'`

(nucleaizer_backend/Mask_RCNN_tf2/mrcnn/utils.py:571)

I will try if I can switch to an older version but this is for another issue and for Monday :)

Thank again for your swiftness with this issue, much appreciated ! 

Best

**Comment by etasnadi** [comment]
np.x where x is a type is deprecated in favor of x since numpy 1.24, so it is normal if it crashes with numpy >= 1.24

You can temporarily fix the issue by installing to a numpy version < 1.24 until I port the plugin to newer numpy versions.

**Comment by ebouilhol** [comment]
Up and running ! You are the best !

Thanks a lot !
